#include <list>
#include <stack>
#include <cstdio>
#include <iostream>
#include <exception>
#include <cstring>
#include <iostream>
#include <stack>
#include <assert.h>
#include <vector>
#include <array>
#include "Array.h"
#include "List.h"
#include "Tree.h"
#include "BinaryTree.h"