#include <list>
#include <stack>
#include <cstdio>
#include <iostream>
#include <exception>
#include <cstring>
#include <string>
#include <stack>
#include <assert.h>
#include <vector>
#include <queue>
#include <array>
#include <set>
#include <functional>
#include <algorithm>
#include <map>
#include <math.h>
#include <unordered_map>
#include <unordered_set>
#include <bitset>
#include <numeric>
#include <bits/stdc++.h>
#include <mutex>
#include <thread>
#include <atomic>
#include <condition_variable>
#include "Array.h"
#include "List.h"
#include "Tree.h"
#include "BinaryTree.h"

using namespace std;